/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSyncAttendanceRouteImport } from './routes/api/sync-attendance'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai-status'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminLiveActivityRouteImport } from './routes/admin/live-activity'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAcademicMonitoringRouteImport } from './routes/admin/academic-monitoring'
import { Route as AuthenticatedPaperSimplifierRouteImport } from './routes/_authenticated/paper-simplifier'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppStudentsRouteImport } from './routes/_authenticated/app.students'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppResumeBuilderRouteImport } from './routes/_authenticated/app.resume-builder'
import { Route as AuthenticatedAppResumeAnalyzerRouteImport } from './routes/_authenticated/app.resume-analyzer'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppExtraRouteImport } from './routes/_authenticated/app.extra'
import { Route as AuthenticatedAppConversionsRouteImport } from './routes/_authenticated/app.conversions'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppClassroomRouteImport } from './routes/_authenticated/app.classroom'
import { Route as AuthenticatedAppClassManagementRouteImport } from './routes/_authenticated/app.class-management'
import { Route as AuthenticatedAppCareerRoadmapRouteImport } from './routes/_authenticated/app.career-roadmap'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/app.attendance'
import { Route as AuthenticatedAppAssignmentsRouteImport } from './routes/_authenticated/app.assignments'
import { Route as AuthenticatedAppAssignCrRouteImport } from './routes/_authenticated/app.assign-cr'
import { Route as AuthenticatedAppAnnouncementsRouteImport } from './routes/_authenticated/app.announcements'
import { Route as AuthenticatedAppAiAssistantRouteImport } from './routes/_authenticated/app.ai-assistant'
import { Route as AuthenticatedAppThreadIdRouteImport } from './routes/_authenticated/app.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSyncAttendanceRoute = ApiSyncAttendanceRouteImport.update({
  id: '/api/sync-attendance',
  path: '/api/sync-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai-status',
  path: '/api/ai-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiveActivityRoute = AdminLiveActivityRouteImport.update({
  id: '/live-activity',
  path: '/live-activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAcademicMonitoringRoute = AdminAcademicMonitoringRouteImport.update({
  id: '/academic-monitoring',
  path: '/academic-monitoring',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedPaperSimplifierRoute =
  AuthenticatedPaperSimplifierRouteImport.update({
    id: '/paper-simplifier',
    path: '/paper-simplifier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStudentsRoute =
  AuthenticatedAppStudentsRouteImport.update({
    id: '/app/students',
    path: '/app/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppResumeBuilderRoute =
  AuthenticatedAppResumeBuilderRouteImport.update({
    id: '/app/resume-builder',
    path: '/app/resume-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppResumeAnalyzerRoute =
  AuthenticatedAppResumeAnalyzerRouteImport.update({
    id: '/app/resume-analyzer',
    path: '/app/resume-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppExtraRoute = AuthenticatedAppExtraRouteImport.update({
  id: '/app/extra',
  path: '/app/extra',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppConversionsRoute =
  AuthenticatedAppConversionsRouteImport.update({
    id: '/app/conversions',
    path: '/app/conversions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/app/community',
    path: '/app/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppClassroomRoute =
  AuthenticatedAppClassroomRouteImport.update({
    id: '/app/classroom',
    path: '/app/classroom',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppClassManagementRoute =
  AuthenticatedAppClassManagementRouteImport.update({
    id: '/app/class-management',
    path: '/app/class-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCareerRoadmapRoute =
  AuthenticatedAppCareerRoadmapRouteImport.update({
    id: '/app/career-roadmap',
    path: '/app/career-roadmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/app/attendance',
    path: '/app/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssignmentsRoute =
  AuthenticatedAppAssignmentsRouteImport.update({
    id: '/app/assignments',
    path: '/app/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssignCrRoute =
  AuthenticatedAppAssignCrRouteImport.update({
    id: '/app/assign-cr',
    path: '/app/assign-cr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAnnouncementsRoute =
  AuthenticatedAppAnnouncementsRouteImport.update({
    id: '/app/announcements',
    path: '/app/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAiAssistantRoute =
  AuthenticatedAppAiAssistantRouteImport.update({
    id: '/app/ai-assistant',
    path: '/app/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppThreadIdRoute =
  AuthenticatedAppThreadIdRouteImport.update({
    id: '/app/$threadId',
    path: '/app/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/admin/academic-monitoring': typeof AdminAcademicMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/live-activity': typeof AdminLiveActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sync-attendance': typeof ApiSyncAttendanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/ai-assistant': typeof AuthenticatedAppAiAssistantRoute
  '/app/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/app/assign-cr': typeof AuthenticatedAppAssignCrRoute
  '/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/app/class-management': typeof AuthenticatedAppClassManagementRoute
  '/app/classroom': typeof AuthenticatedAppClassroomRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/app/extra': typeof AuthenticatedAppExtraRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/app/resume-builder': typeof AuthenticatedAppResumeBuilderRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/students': typeof AuthenticatedAppStudentsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/admin/academic-monitoring': typeof AdminAcademicMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/live-activity': typeof AdminLiveActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sync-attendance': typeof ApiSyncAttendanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/ai-assistant': typeof AuthenticatedAppAiAssistantRoute
  '/app/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/app/assign-cr': typeof AuthenticatedAppAssignCrRoute
  '/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/app/class-management': typeof AuthenticatedAppClassManagementRoute
  '/app/classroom': typeof AuthenticatedAppClassroomRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/app/extra': typeof AuthenticatedAppExtraRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/app/resume-builder': typeof AuthenticatedAppResumeBuilderRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/students': typeof AuthenticatedAppStudentsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/paper-simplifier': typeof AuthenticatedPaperSimplifierRoute
  '/admin/academic-monitoring': typeof AdminAcademicMonitoringRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/live-activity': typeof AdminLiveActivityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sync-attendance': typeof ApiSyncAttendanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/_authenticated/app/ai-assistant': typeof AuthenticatedAppAiAssistantRoute
  '/_authenticated/app/announcements': typeof AuthenticatedAppAnnouncementsRoute
  '/_authenticated/app/assign-cr': typeof AuthenticatedAppAssignCrRoute
  '/_authenticated/app/assignments': typeof AuthenticatedAppAssignmentsRoute
  '/_authenticated/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/app/career-roadmap': typeof AuthenticatedAppCareerRoadmapRoute
  '/_authenticated/app/class-management': typeof AuthenticatedAppClassManagementRoute
  '/_authenticated/app/classroom': typeof AuthenticatedAppClassroomRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/conversions': typeof AuthenticatedAppConversionsRoute
  '/_authenticated/app/extra': typeof AuthenticatedAppExtraRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/resume-analyzer': typeof AuthenticatedAppResumeAnalyzerRoute
  '/_authenticated/app/resume-builder': typeof AuthenticatedAppResumeBuilderRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/students': typeof AuthenticatedAppStudentsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/paper-simplifier'
    | '/admin/academic-monitoring'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/live-activity'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/api/ai-status'
    | '/api/chat'
    | '/api/sync-attendance'
    | '/auth/callback'
    | '/admin/'
    | '/app/$threadId'
    | '/app/ai-assistant'
    | '/app/announcements'
    | '/app/assign-cr'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/career-roadmap'
    | '/app/class-management'
    | '/app/classroom'
    | '/app/community'
    | '/app/conversions'
    | '/app/extra'
    | '/app/profile'
    | '/app/resume-analyzer'
    | '/app/resume-builder'
    | '/app/settings'
    | '/app/students'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/paper-simplifier'
    | '/admin/academic-monitoring'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/live-activity'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/api/ai-status'
    | '/api/chat'
    | '/api/sync-attendance'
    | '/auth/callback'
    | '/admin'
    | '/app/$threadId'
    | '/app/ai-assistant'
    | '/app/announcements'
    | '/app/assign-cr'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/career-roadmap'
    | '/app/class-management'
    | '/app/classroom'
    | '/app/community'
    | '/app/conversions'
    | '/app/extra'
    | '/app/profile'
    | '/app/resume-analyzer'
    | '/app/resume-builder'
    | '/app/settings'
    | '/app/students'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/paper-simplifier'
    | '/admin/academic-monitoring'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/live-activity'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/api/ai-status'
    | '/api/chat'
    | '/api/sync-attendance'
    | '/auth/callback'
    | '/admin/'
    | '/_authenticated/app/$threadId'
    | '/_authenticated/app/ai-assistant'
    | '/_authenticated/app/announcements'
    | '/_authenticated/app/assign-cr'
    | '/_authenticated/app/assignments'
    | '/_authenticated/app/attendance'
    | '/_authenticated/app/career-roadmap'
    | '/_authenticated/app/class-management'
    | '/_authenticated/app/classroom'
    | '/_authenticated/app/community'
    | '/_authenticated/app/conversions'
    | '/_authenticated/app/extra'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/resume-analyzer'
    | '/_authenticated/app/resume-builder'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/students'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSyncAttendanceRoute: typeof ApiSyncAttendanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/sync-attendance': {
      id: '/api/sync-attendance'
      path: '/api/sync-attendance'
      fullPath: '/api/sync-attendance'
      preLoaderRoute: typeof ApiSyncAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-status': {
      id: '/api/ai-status'
      path: '/api/ai-status'
      fullPath: '/api/ai-status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/live-activity': {
      id: '/admin/live-activity'
      path: '/live-activity'
      fullPath: '/admin/live-activity'
      preLoaderRoute: typeof AdminLiveActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/academic-monitoring': {
      id: '/admin/academic-monitoring'
      path: '/academic-monitoring'
      fullPath: '/admin/academic-monitoring'
      preLoaderRoute: typeof AdminAcademicMonitoringRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/paper-simplifier': {
      id: '/_authenticated/paper-simplifier'
      path: '/paper-simplifier'
      fullPath: '/paper-simplifier'
      preLoaderRoute: typeof AuthenticatedPaperSimplifierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/students': {
      id: '/_authenticated/app/students'
      path: '/app/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AuthenticatedAppStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/resume-builder': {
      id: '/_authenticated/app/resume-builder'
      path: '/app/resume-builder'
      fullPath: '/app/resume-builder'
      preLoaderRoute: typeof AuthenticatedAppResumeBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/resume-analyzer': {
      id: '/_authenticated/app/resume-analyzer'
      path: '/app/resume-analyzer'
      fullPath: '/app/resume-analyzer'
      preLoaderRoute: typeof AuthenticatedAppResumeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/extra': {
      id: '/_authenticated/app/extra'
      path: '/app/extra'
      fullPath: '/app/extra'
      preLoaderRoute: typeof AuthenticatedAppExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/conversions': {
      id: '/_authenticated/app/conversions'
      path: '/app/conversions'
      fullPath: '/app/conversions'
      preLoaderRoute: typeof AuthenticatedAppConversionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/app/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/classroom': {
      id: '/_authenticated/app/classroom'
      path: '/app/classroom'
      fullPath: '/app/classroom'
      preLoaderRoute: typeof AuthenticatedAppClassroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/class-management': {
      id: '/_authenticated/app/class-management'
      path: '/app/class-management'
      fullPath: '/app/class-management'
      preLoaderRoute: typeof AuthenticatedAppClassManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/career-roadmap': {
      id: '/_authenticated/app/career-roadmap'
      path: '/app/career-roadmap'
      fullPath: '/app/career-roadmap'
      preLoaderRoute: typeof AuthenticatedAppCareerRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/attendance': {
      id: '/_authenticated/app/attendance'
      path: '/app/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assignments': {
      id: '/_authenticated/app/assignments'
      path: '/app/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AuthenticatedAppAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assign-cr': {
      id: '/_authenticated/app/assign-cr'
      path: '/app/assign-cr'
      fullPath: '/app/assign-cr'
      preLoaderRoute: typeof AuthenticatedAppAssignCrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/announcements': {
      id: '/_authenticated/app/announcements'
      path: '/app/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AuthenticatedAppAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ai-assistant': {
      id: '/_authenticated/app/ai-assistant'
      path: '/app/ai-assistant'
      fullPath: '/app/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAppAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$threadId': {
      id: '/_authenticated/app/$threadId'
      path: '/app/$threadId'
      fullPath: '/app/$threadId'
      preLoaderRoute: typeof AuthenticatedAppThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPaperSimplifierRoute: typeof AuthenticatedPaperSimplifierRoute
  AuthenticatedAppThreadIdRoute: typeof AuthenticatedAppThreadIdRoute
  AuthenticatedAppAiAssistantRoute: typeof AuthenticatedAppAiAssistantRoute
  AuthenticatedAppAnnouncementsRoute: typeof AuthenticatedAppAnnouncementsRoute
  AuthenticatedAppAssignCrRoute: typeof AuthenticatedAppAssignCrRoute
  AuthenticatedAppAssignmentsRoute: typeof AuthenticatedAppAssignmentsRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppCareerRoadmapRoute: typeof AuthenticatedAppCareerRoadmapRoute
  AuthenticatedAppClassManagementRoute: typeof AuthenticatedAppClassManagementRoute
  AuthenticatedAppClassroomRoute: typeof AuthenticatedAppClassroomRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppConversionsRoute: typeof AuthenticatedAppConversionsRoute
  AuthenticatedAppExtraRoute: typeof AuthenticatedAppExtraRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppResumeAnalyzerRoute: typeof AuthenticatedAppResumeAnalyzerRoute
  AuthenticatedAppResumeBuilderRoute: typeof AuthenticatedAppResumeBuilderRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStudentsRoute: typeof AuthenticatedAppStudentsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPaperSimplifierRoute: AuthenticatedPaperSimplifierRoute,
  AuthenticatedAppThreadIdRoute: AuthenticatedAppThreadIdRoute,
  AuthenticatedAppAiAssistantRoute: AuthenticatedAppAiAssistantRoute,
  AuthenticatedAppAnnouncementsRoute: AuthenticatedAppAnnouncementsRoute,
  AuthenticatedAppAssignCrRoute: AuthenticatedAppAssignCrRoute,
  AuthenticatedAppAssignmentsRoute: AuthenticatedAppAssignmentsRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppCareerRoadmapRoute: AuthenticatedAppCareerRoadmapRoute,
  AuthenticatedAppClassManagementRoute: AuthenticatedAppClassManagementRoute,
  AuthenticatedAppClassroomRoute: AuthenticatedAppClassroomRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppConversionsRoute: AuthenticatedAppConversionsRoute,
  AuthenticatedAppExtraRoute: AuthenticatedAppExtraRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppResumeAnalyzerRoute: AuthenticatedAppResumeAnalyzerRoute,
  AuthenticatedAppResumeBuilderRoute: AuthenticatedAppResumeBuilderRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStudentsRoute: AuthenticatedAppStudentsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAcademicMonitoringRoute: typeof AdminAcademicMonitoringRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminLiveActivityRoute: typeof AdminLiveActivityRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAcademicMonitoringRoute: AdminAcademicMonitoringRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminLiveActivityRoute: AdminLiveActivityRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSyncAttendanceRoute: ApiSyncAttendanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
